### PR TITLE
Add hardware perf measures

### PR DESCRIPTION
**Pull request by OlivierNicole**
Simply add the missing glue. I also made the unit labels fit within 5 characters.

### CODE REVIEW

**Comment by dinosaure** [comment]
Thanks! I think it will be ready to merge.

**Comment by OlivierNicole** [comment]
Actually, maybe just wait a bit: I realized that this code gives me a “No such file or directory” error when using the library, because of the `ref_cpu_cycles` apparently not existing on all kernels (processors?).

Edit.: and this, even when not trying to use the `ref_cpu_cycles` measure.

**Comment by OlivierNicole** [comment]
I have removed the measures that are not present on my machine and prevent the library from loading. I believe it should be more usable now.

**Comment by dinosaure** [comment]
The PR is fine, the error on the documentation is due to a downgrade of `ocplib-json-typed` which is not really expected. Ready for a release so. Thanks!

**Pull request merged**
